// src/plotting-engine/config.ts

export const DEPTH_COL = 'DEPTH';
export const LINE_WIDTH = 0.9;

// Definisikan tipe kunci yang valid dari ratio_plots
export type TrackKey = keyof typeof ratio_plots;

// --- PERBAIKAN: Tambahkan tipe eksplisit menggunakan Record<string, ...> ---

export const data_col: Record<string, readonly string[]> = { 'DNS': ['DNS'], 'MARKER': ['MARKER'], 'GR': ['GR'], 'GR_NORM': ['GR_NORM'], 'GR_DUAL': ['GR', 'GR_NORM'], 'RT': ['RT'], 'RT_RO': ['RT','RO'], 'X_RT_RO': ['RT_RO'], 'NPHI_RHOB_NON_NORM': ['NPHI','RHOB'], 'RHOB': ['RHOB'], 'NPHI_RHOB': ['NPHI','RHOB','NPHI_NORM','RHOB_NORM_NPHI'], 'SW': ['SW'], 'PHIE_PHIT': ['PHIE', 'PHIT'], 'PERM': ['PERM'], 'VCL': ['VCL'], 'RWAPP_RW': ['RWAPP','RW'], 'X_RWA_RW': ['RWA_RW'], 'RT_F': ['RT','F'], 'X_RT_F': ['RT_F'], 'RT_RHOB': ['RT', 'RHOB' ,'RT_NORM', 'RHOB_NORM_RT'], 'X_RT_RHOB': ['RT_RHOB'], 'TEST': ['TEST'], 'XPT': ['XPT'], 'RT_RGSA': ['RT', 'RGSA'], 'NPHI_NGSA': ['NPHI', 'NGSA'], 'RHOB_DGSA': ['RHOB', 'DGSA'], 'ZONA': ['ZONA'], 'VSH': ['VSH'], 'SP': ['SP'], 'VSH_LINEAR': ['VSH_LINEAR'], 'VSH_DN': ['VSH_DN'], 'VSH_SP': ['VSH_SP'], 'PHIE_DEN':['PHIE','PHIE_DEN'], 'PHIT_DEN':['PHIT','PHIT_DEN'], 'RESERVOIR_CLASS': ['RESERVOIR_CLASS'], 'RWA': ['RWA_FULL','RWA_SIMPLE','RWA_TAR'], 'PHIE': ['PHIE'], 'RT_GR': ['RT','GR','RT_NORM', 'GR_NORM_RT'], 'RT_PHIE':['RT','PHIE','RT_NORM', 'PHIE_NORM_RT'], 'RGBE': ['RGBE'], 'RPBE': ['RPBE'], 'SWARRAY': ['SWARRAY_10','SWARRAY_25'], 'SWGRAD': ['SWGRAD'] };
export const unit_col: Record<string, readonly string[]> = { 'DNS': [''], 'MARKER': [''], 'GR_NORM': ['GAPI'], 'GR': ['GAPI'], 'GR_DUAL': ['GAPI', 'GAPI'], 'RT': ['OHMM'], 'RT_RO': ['OHMM','OHMM'], 'X_RT_RO': ['V/V'], 'NPHI_RHOB_NON_NORM': ['V/V','G/C3'], 'NPHI_RHOB': ['V/V','G/C3','V/V','G/C3'], 'RHOB': ['G/C3'], 'SW': ['DEC'], 'PHIE_PHIT': ['V/V', 'V/V'], 'PERM': ['mD'], 'VCL': ['V/V'], 'RWAPP_RW': ['OHMM','OHMM'], 'X_RWA_RW': ['V/V'], 'RT_F': ['OHMM','V/V'], 'X_RT_F': ['V/V'], 'RT_RHOB': ['OHMM', 'G/C3','OHMM', 'G/C3'], 'X_RT_RHOB': ['V/V'], 'TEST': ['V/V'], 'CLASS': ['V/V'], 'CTC': ['V/V'], 'XPT': [''], 'RT_RGSA': ['OHMM', ''], 'NPHI_NGSA': ['V/V', ''], 'RHOB_DGSA': ['G/C3', ''], 'ZONA': [''], 'VSH': ['V/V'], 'SP': ['MV'], 'VSH_LINEAR': ['V/V'], 'VSH_DN': ['V/V'], 'VSH_SP': ['V/V'], 'PHIE_DEN':['',''], 'PHIT_DEN':['',''], 'RESERVOIR_CLASS': [''], 'RWA': ['OHMM','OHMM','OHMM'], 'PHIE': [''], 'RT_GR': ['OHMM','GAPI','OHMM','GAPI'], 'RT_PHIE':['OHMM','','OHMM',''], 'RGBE': [''], 'RPBE': [''], 'SWARRAY': ['V/V','V/V'], 'SWGRAD': ['V/V'] };
export const color_col: Record<string, readonly string[]> = { 'DNS': ['darkgreen'], 'MARKER': ['rgba(62, 62, 62,1)'], 'GR_NORM': ['orange'], 'GR_DUAL': ['darkgreen', 'orange'], 'GR': ['darkgreen'], 'RT': ['tomato'], 'RT_RO': ['tomato', '#990099'], 'X_RT_RO': ['rgba(62, 62, 62,1)'], 'NPHI_RHOB_NON_NORM': ['royalblue','tomato'], 'NPHI_RHOB': ['royalblue','tomato','royalblue','tomato'], 'RHOB': ['tomato'], 'SW': ['royalblue'], 'PHIE_PHIT': ['darkblue','#0099C6'], 'PERM': ['royalblue'], 'VCL': ['rgba(62, 62, 62,1)'], 'RWAPP_RW': ['rgba(62, 62, 62,1)','royalblue'], 'X_RWA_RW': ['rgba(62, 62, 62,1)'], 'RT_F': ['tomato','#0099C6'], 'X_RT_F': ['rgba(62, 62, 62,1)'], 'RT_RHOB': ['tomato','rgba(62, 62, 62,1)','tomato','#109618'], 'X_RT_RHOB': ['rgba(62, 62, 62,1)'], 'TEST': ['rgba(62, 62, 62,1)'], 'CLASS': ['rgba(62, 62, 62,1)'], 'CTC': ['rgba(62, 62, 62,1)'], 'XPT': ['rgba(62, 62, 62,1)'], 'RT_RGSA': ['tomato', 'royalblue'], 'NPHI_NGSA': ['tomato', '#109618'], 'RHOB_DGSA': ['tomato', '#109618'], 'ZONA': ['rgba(62, 62, 62,1)'], 'VSH': ['darkblue'], 'SP': ['darkblue'], 'VSH_LINEAR': ['darkblue'], 'VSH_DN': ['darkblue'], 'VSH_SP': ['darkblue'], 'PHIE_DEN':['darkblue','royalblue'], 'PHIT_DEN':['tomato', '#FF9900'], 'RESERVOIR_CLASS': ['rgba(62, 62, 62,1)'], 'RWA': ['darkblue','darkgreen','tomato'], 'PHIE': ['darkblue'], 'RT_GR': ['tomato','darkgreen','tomato','darkgreen'], 'RT_PHIE':['tomato','darkblue','tomato','darkblue'], 'RGBE': ['rgba(62, 62, 62,1)'], 'RPBE': ['rgba(62, 62, 62,1)'], 'SWARRAY': ['darkblue','orange'], 'SWGRAD': ['darkgreen'] };
export const range_col: Record<string, readonly (readonly [number, number])[]> = { 'GR': [[0,250]], 'GR_NORM': [[0,250]], 'GR_DUAL': [[0, 250], [0, 250]], 'RT': [[0.2, 2000]], 'RT_RO': [[0.2, 2000], [0.2, 2000]], 'X_RT_RO': [[0,4]], 'NPHI_RHOB_NON_NORM': [[0.6, 0],[1.71,2.71]], 'NPHI_RHOB': [[0.45, -0.15],[1.95,2.95]], 'RHOB': [[1.71, 2.71]], 'SW': [[1, 0]], 'PHIE_PHIT': [[0.5,0],[0.5,0]], 'PERM': [[0.02, 2000]], 'VCL': [[0,1]], 'RWAPP_RW': [[0.01, 1000],[0.01, 1000]], 'X_RWA_RW': [[0,4]], 'RT_F': [[0.2, 2000], [0.2, 2000]], 'X_RT_F': [[0,2]], 'RT_RHOB': [[0.2, 2000],[1.95,2.95]], 'X_RT_RHOB': [[-0.5,0.5]], 'XPT': [[0,1]], 'RT_RGSA': [[0.2, 2000], [0.2, 2000]], 'NPHI_NGSA': [[0.6, 0], [0.6, 0]], 'RHOB_DGSA': [[1.71, 2.71], [1.71, 2.71]], 'VSH': [[0, 1]], 'SP': [[-160,40]], 'VSH_LINEAR': [[0, 1]], 'VSH_DN': [[0, 1]], 'VSH_SP': [[0, 1]], 'PHIE_DEN':[[0,1],[0,1]], 'PHIT_DEN':[[0,1],[0,1]], 'RWA': [[0,60],[0,60],[0,60]], 'PHIE': [[0.6,0]], 'RT_GR': [[0.2, 2000],[0,250],[0.2, 2000],[0,250]], 'RT_PHIE':[[0.2, 2000],[0.6,0],[0.2, 2000],[0.6,0]], 'SWARRAY': [[1,0],[1,0]], 'SWGRAD': [[-2,2]] };
export const ratio_plots: Record<string, number> = { 'MARKER': 0.5, 'GR': 1, 'GR_NORM': 1, 'GR_DUAL': 1, 'RT': 1, 'RT_RO': 1, 'X_RT_RO': 0.5, 'NPHI_RHOB_NON_NORM': 1, 'NPHI_RHOB': 1, 'RHOB': 1, 'SW': 1, 'PHIE_PHIT': 1, 'PERM': 1, 'VCL': 1, 'RWAPP_RW': 1, 'X_RWA_RW': 0.5, 'RT_F': 1, 'X_RT_F': 0.5, 'RT_RHOB': 1, 'X_RT_RHOB': 0.5, 'TEST': 0.5, 'CLASS': 0.5, 'CTC': 0.5, 'XPT': 1, 'RT_RGSA': 1, 'NPHI_NGSA': 1, 'RHOB_DGSA': 1, 'ZONA': 1, 'VSH' : 1, 'SP' : 1, 'VSH_LINEAR' : 1, 'VSH_DN' : 1, 'VSH_SP' : 1, 'PHIE_DEN':1, 'PHIT_DEN':1, 'RESERVOIR_CLASS': 0.5, 'RWA': 1, 'PHIE': 1, 'RT_GR': 1, 'RT_PHIE': 1, 'RGBE': 0.5, 'RPBE': 0.5, 'SWARRAY': 1, 'SWGRAD': 1 };